config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about" => "pages#about" # creates about_path
  get "about" => "pages#www.ugeducation.ucla.edu/counseling/articulation-faqs.html"
  get "button" => "pages#Yespage"

end

app/models/pins.rb
class Pin < ActiveRecord::Base

		has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "UCLA COLLEGE ACADEMIC COUNSELING", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "HOME", root_path %></li>
        <li><%= link_to "FAQS", about_path %></li>
        <li> <a href="http://my.ucla.edu">MYUCLA</a> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CAN I HAZ APPT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body> 

	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/Yespage.html.erb
<div class="yespage">
			<div> <h1>Yes!</h1>
	<p> 
	<h2> Please select from the available times:</h2>
	</p>
	</div>
</div>

app/views/pages/about.html.erb
<div class="about">
	<TEXT= "white">
	<h1>FAQS</h1>
		<p>If you are an undergraduate in the UCLA College, we encourage you to consult these pages to educate yourself about the rules affecting your academic career and to explore the many resources available to you here at UCLA. Please remember, however, that each student's situation is unique, and that you should use this site as a supplement to, rather than a substitute for, meeting with your UCLA College academic advisor.</p>

		<p>Click <a href="http://www.ugeducation.ucla.edu/counseling/faqs.html"> here </a> for answers to FAQs.</p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
		<div class="getappointment center">
			<div> <h1>Can I Make An Appointment Today?</h1>

		<div class="button">
		<p>
		<%= link_to "Click Here To Find Out", button_path, class: "btn btn-primary btn-lg" %>
		</p>
		</div>
		</div>
	</div>
</div>